name: CI

on: [push]

env:
  CI: true
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Configure Git
        run: |
          git config --global user.email "ezra.m.brooks@gmail.com"
          git config --global user.name "Ezra Brooks"
      # retrieved from https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Yarn test
        run: yarn test

      - name: Git clone Pages repo
        run: git clone git@github.com:EzraBrooks/EzraBrooks.github.io.git pages

      - name: Remove contents of pages folder
        run: |
          rm -rf pages/*
          rm pages/.nojekyll

      - name: Yarn build
        run: yarn build

      - name: Copy build output
        run: cp -r build/* pages/

      - name: Add and commit changes
        working-directory: ./pages
        run: |
          git add .
          ls -axl
          git commit -m "Update from source"

      - name: Git push
        working-directory: ./pages
        run: git push
        if: github.ref == 'master'
